################### MangoHud: Horizontal + RAM + SWAP + Frame ###################

legacy_layout=false
horizontal
table_columns=1

font_size=19
background_alpha=0.4
round_corners=10
background_color=000000
text_color=FFFFFF

position=top-left

# === GPU ===
gpu_stats
gpu_load
gpu_temp
gpu_junction_temp
gpu_power
vram

# === CPU ===
cpu_stats
cpu_load
cpu_mhz
cpu_temp

# === Memory ===
ram
swap

# === FPS & Frametimes ===
fps
refresh_rate
#fps_metrics=avg,0.01
frame_timing
resolution
gamemode
winesync
display_server

frametime_color=00FF00
fps_color_change
fps_color=B22222,FDFD09,39F900
fps_value=30,60
fps_limit=0,30,40,45,60,75,120
toggle_fps_limit=F3
